feat: injector and injections unit. tests and sample WASM file
LimeChain/parachain-conformance-dev pull request #8
Opened 2023-07-25 11:05 UTC by mikirov

- Separate FunctionMapper functionality into separate getters so they can be tested
- implement unit tests based on sample WASM file
- implement unit tests for correct instructions being present in target WASM after injecting

2023-07-25 11:45 UTC, reo101 requested changes
Good job on the PR :smile:. I've left a few requests for changes

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injections.rs
> +        let index: u32 = module.get_malloc_index().unwrap() as u32;
Unnecessary type annotation

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injector.rs
> +        d.push("test.wasm");
Might want to extract this `PathBuf` (or even the loaded module for that matter) as a constant. You can test the module loading in isolation.

2023-07-25 11:45 UTC, reo101 commented on test.wasm
Generally not a good idea to store binary blobs in git (consider using git-lfs or similar)

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injector.rs
> +            .unwrap();
You're are already in a function returning a `Result`. Please propagate the errors correctly (no `unwrap`s). Applies to the above 4 statements in this function.

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injections.rs
> +            .collect::<Vec<Instruction>>();
Clever monadic usage, nice :smile:

You could also consider something like this, for readability:

```rust
let expected = vec![Instruction::I32Const(33_554_431), Instruction::Call(index)]
  .into_iter()
  .cycle()
  .take(16)
  .collect::<Vec<_>>();
```

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injector.rs
> +    // NOTE VALUES ARE FOR TEST WASM ONLY AND WILL DIFFER FOR DIFFERENT WASM BLOBS!!!
You could use `// NOTE: ...` to be consistent with the rest of the comments in the project. Also, consider using a higher severity - like `WARNING`.

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injector.rs
>          // Extract the `${function_name}` function_body
A newline for consistency would be nice here :smile:

2023-07-25 11:45 UTC, reo101 commented on src/injecting/injector.rs
> +        let malloc_index = self.get_malloc_index().unwrap();
You could either add a short comment here (regarding why this is complex enough that it needs to be abstracted away in a function).

I've commented about the use of `.unwrap()` below.

2023-07-25 12:53 UTC, mikirov commented on test.wasm
True, however for one file i was willing to make an exception. If we go to git-lfs there is no easy way to go back (at least in by experience it was clunky). Do we need it for something other than this file? Potentially in the future?

2023-07-26 04:44 UTC, reo101 requested changes

2023-07-26 04:44 UTC, reo101 commented on src/injecting/injections.rs
> +        .collect::<Vec<_>>();
Please format this

2023-07-26 04:44 UTC, reo101 commented on src/injecting/injector.rs
> +        };
This is redundant, you can use the `?` shorthand:

```rust
// Get the global function index of the dynamic memory allocation method
let malloc_index = self.get_malloc_index()?;
```

(Applies to the whole function)

2023-07-26 04:48 UTC, reo101 commented on test.wasm
Fair, if it is only one fine - yes, no problem. In the future we might get around to testing lots of different wasms which would be supplied in other ways (maybe a directory filled with fresh ones, ready for injection and testing).

But alas I digress, it's fine for now / can be fixed up later down the line (would still remain in git history tho).

2023-07-26 05:32 UTC, dimitrovmaksim commented on test.wasm
I'll also suggest moving it into a folder (for example `wasm`) and not leaving the file in the root

2023-07-26 07:47 UTC, reo101 requested changes
Apart from that last comment, LGTM

2023-07-26 08:38 UTC, dimitrovmaksim commented on src/injecting/injector.rs
> +    const WASM_PATH: &'static str = concat!(env!("CARGO_MANIFEST_DIR"), "/wasm/test.wasm");
The `wasm` folder is ingored in the .gitignore file. Now the file is no present in the repo.

2023-07-26 11:43 UTC, reo101 approved these changes
LGTM

2023-07-26 11:44 UTC, reo101 commented
There's a typo in the commit name

2023-07-26 11:53 UTC, merged